// lib/theme/theme-context.jsx

/**
 *  * Contexte de thème React
  * Fournit les couleurs et configurations de thème à toute l'application
   */

   import React, { createContext, useContext, useState, useEffect } from 'react';
   import { useColorScheme } from 'react-native';
   import * as SecureStore from 'expo-secure-store';

   const ThemeContext = createContext({
     colors: {},
       theme: 'nexus_blue',
         themeMode: 'system',
           setTheme: () => {},
             setThemeMode: () => {},
             });

             // Thèmes disponibles
             const themes = {
               nexus_blue: {
                   light: {
                         primary: '#5B7CFA',
                               secondary: '#7D9AFC',
                                     background: '#FFFFFF',
                                           surface: '#F8FAFC',
                                                 surfaceVariant: '#F1F5F9',
                                                       textPrimary: '#0F172A',
                                                             textSecondary: '#475569',
                                                                   border: '#E2E8F0',
                                                                         success: '#10B981',
                                                                               error: '#EF4444',
                                                                                     warning: '#F59E0B',
                                                                                         },
                                                                                             dark: {
                                                                                                   primary: '#5B7CFA',
                                                                                                         secondary: '#7D9AFC',
                                                                                                               background: '#0F172A',
                                                                                                                     surface: '#1E293B',
                                                                                                                           surfaceVariant: '#334155',
                                                                                                                                 textPrimary: '#F8FAFC',
                                                                                                                                       textSecondary: '#CBD5E1',
                                                                                                                                             border: '#475569',
                                                                                                                                                   success: '#10B981',
                                                                                                                                                         error: '#EF4444',
                                                                                                                                                               warning: '#F59E0B',
                                                                                                                                                                   },
                                                                                                                                                                     },
                                                                                                                                                                     };

                                                                                                                                                                     export function ThemeProvider({ children }) {
                                                                                                                                                                       const colorScheme = useColorScheme();
                                                                                                                                                                         const [theme, setTheme] = useState('nexus_blue');
                                                                                                                                                                           const [themeMode, setThemeMode] = useState('system');
                                                                                                                                                                             const [colors, setColors] = useState(themes.nexus_blue.light);

                                                                                                                                                                               // Initialiser le thème
                                                                                                                                                                                 useEffect(() => {
                                                                                                                                                                                     loadTheme();
                                                                                                                                                                                       }, []);

                                                                                                                                                                                         const loadTheme = async () => {
                                                                                                                                                                                             try {
                                                                                                                                                                                                   const savedTheme = await SecureStore.getItemAsync('app_theme');
                                                                                                                                                                                                         const savedMode = await SecureStore.getItemAsync('theme_mode');
                                                                                                                                                                                                               
                                                                                                                                                                                                                     if (savedTheme && themes[savedTheme]) {
                                                                                                                                                                                                                             setTheme(savedTheme);
                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                               if (savedMode) {
                                                                                                                                                                                                                                                       setThemeMode(savedMode);
                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                         updateColors(savedTheme || 'nexus_blue', savedMode || 'system');
                                                                                                                                                                                                                                                                             } catch (error) {
                                                                                                                                                                                                                                                                                   console.error('Error loading theme:', error);
                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                         };

                                                                                                                                                                                                                                                                                           const updateColors = (themeId, mode) => {
                                                                                                                                                                                                                                                                                               const selectedTheme = themes[themeId] || themes.nexus_blue;
                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                       let effectiveMode = mode === 'system' ? colorScheme : mode;
                                                                                                                                                                                                                                                                                                           if (!effectiveMode || !selectedTheme[effectiveMode]) {
                                                                                                                                                                                                                                                                                                                 effectiveMode = 'light';
                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                             setColors(selectedTheme[effectiveMode]);
                                                                                                                                                                                                                                                                                                                               };

                                                                                                                                                                                                                                                                                                                                 // Mettre à jour les couleurs quand le thème ou le mode change
                                                                                                                                                                                                                                                                                                                                   useEffect(() => {
                                                                                                                                                                                                                                                                                                                                       updateColors(theme, themeMode);
                                                                                                                                                                                                                                                                                                                                         }, [theme, themeMode, colorScheme]);

                                                                                                                                                                                                                                                                                                                                           const handleSetTheme = async (themeId) => {
                                                                                                                                                                                                                                                                                                                                               if (!themes[themeId]) return;
                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                       setTheme(themeId);
                                                                                                                                                                                                                                                                                                                                                           await SecureStore.setItemAsync('app_theme', themeId);
                                                                                                                                                                                                                                                                                                                                                             };

                                                                                                                                                                                                                                                                                                                                                               const handleSetThemeMode = async (mode) => {
                                                                                                                                                                                                                                                                                                                                                                   if (!['light', 'dark', 'system'].includes(mode)) return;
                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                           setThemeMode(mode);
                                                                                                                                                                                                                                                                                                                                                                               await SecureStore.setItemAsync('theme_mode', mode);
                                                                                                                                                                                                                                                                                                                                                                                 };

                                                                                                                                                                                                                                                                                                                                                                                   const value = {
                                                                                                                                                                                                                                                                                                                                                                                       colors,
                                                                                                                                                                                                                                                                                                                                                                                           theme,
                                                                                                                                                                                                                                                                                                                                                                                               themeMode,
                                                                                                                                                                                                                                                                                                                                                                                                   setTheme: handleSetTheme,
                                                                                                                                                                                                                                                                                                                                                                                                       setThemeMode: handleSetThemeMode,
                                                                                                                                                                                                                                                                                                                                                                                                         };

                                                                                                                                                                                                                                                                                                                                                                                                           return (
                                                                                                                                                                                                                                                                                                                                                                                                               <ThemeContext.Provider value={value}>
                                                                                                                                                                                                                                                                                                                                                                                                                     {children}
                                                                                                                                                                                                                                                                                                                                                                                                                         </ThemeContext.Provider>
                                                                                                                                                                                                                                                                                                                                                                                                                           );
                                                                                                                                                                                                                                                                                                                                                                                                                           }

                                                                                                                                                                                                                                                                                                                                                                                                                           export function useTheme() {
                                                                                                                                                                                                                                                                                                                                                                                                                             const context = useContext(ThemeContext);
                                                                                                                                                                                                                                                                                                                                                                                                                               if (!context) {
                                                                                                                                                                                                                                                                                                                                                                                                                                   throw new Error('useTheme must be used within a ThemeProvider');
                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                       return context;
                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                       