/**
 *  * Écran de conversation avec une IA
  * Interface de chat complète avec l'IA sélectionnée
   */

   import React, { useState, useEffect, useRef } from 'react';
   import {
     View,
       Text,
         ScrollView,
           TextInput,
             TouchableOpacity,
               SafeAreaView,
                 KeyboardAvoidingView,
                   Platform,
                     ActivityIndicator,
                       Alert,
                       } from 'react-native';
                       import { useRouter, useLocalSearchParams } from 'expo-router';
                       import { Ionicons } from '@expo/vector-icons';

                       // Hooks et services
                       import { useAuth } from '../../../lib/auth/use-auth';
                       import { useTheme } from '../../../lib/theme/theme-context';
                       import { useAnalytics } from '../../../lib/hooks/use-analytics';
                       import { aiManager } from '../../../lib/ai/ai-manager';
                       import { chatPersistence } from '../../../lib/ai/chat-persistence';

                       // Composants
                       import { Loading } from '../../../components/shared/loading';
                       import { MessageBubble } from '../../../components/chat/message-bubble';

                       export default function AIChatScreen() {
                         const router = useRouter();
                           const { id } = useLocalSearchParams();
                             const { user } = useAuth();
                               const { colors } = useTheme();
                                 const { trackEvent } = useAnalytics();

                                   const [loading, setLoading] = useState(true);
                                     const [sending, setSending] = useState(false);
                                       const [message, setMessage] = useState('');
                                         const [chat, setChat] = useState(null);
                                           const [messages, setMessages] = useState([]);
                                             const [aiTyping, setAiTyping] = useState(false);
                                               const [quotaExceeded, setQuotaExceeded] = useState(false);

                                                 const scrollViewRef = useRef(null);
                                                   const inputRef = useRef(null);

                                                     useEffect(() => {
                                                         loadChat();

                                                             trackEvent('ai_chat_opened', {
                                                                   chat_id: id,
                                                                         user_id: user?.id,
                                                                             });
                                                                               }, [id]);

                                                                                 const loadChat = async () => {
                                                                                     try {
                                                                                           setLoading(true);

                                                                                                 const chatData = await chatPersistence.getAIChat(id);

                                                                                                       if (!chatData) {
                                                                                                               Alert.alert('Erreur', 'Conversation introuvable');
                                                                                                                       router.back();
                                                                                                                               return;
                                                                                                                                     }

                                                                                                                                           setChat(chatData);
                                                                                                                                                 setMessages(chatData.messages || []);
                                                                                                                                                       await checkQuotas(chatData);

                                                                                                                                                           } catch (error) {
                                                                                                                                                                 console.error(error);
                                                                                                                                                                       Alert.alert('Erreur', 'Impossible de charger la conversation');
                                                                                                                                                                             router.back();
                                                                                                                                                                                 } finally {
                                                                                                                                                                                       setLoading(false);
                                                                                                                                                                                           }
                                                                                                                                                                                             };

                                                                                                                                                                                               const checkQuotas = async (chatData) => {
                                                                                                                                                                                                   try {
                                                                                                                                                                                                         const ai = aiManager
                                                                                                                                                                                                                 .getAvailableAIs()
                                                                                                                                                                                                                         .find(a => a.id === chatData.aiId);

                                                                                                                                                                                                                               if (!ai) return;

                                                                                                                                                                                                                                     const canUse = await aiManager.quotaManager.canUseAI(
                                                                                                                                                                                                                                             ai.id,
                                                                                                                                                                                                                                                     ai.isFree ? 'free' : 'premium'
                                                                                                                                                                                                                                                           );

                                                                                                                                                                                                                                                                 setQuotaExceeded(!canUse);
                                                                                                                                                                                                                                                                     } catch (error) {
                                                                                                                                                                                                                                                                           console.error(error);
                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                 };
                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                 const sendMessage = async () => {
                                                                                                                                                                                                                                                                                        if (!message.trim() || sending || quotaExceeded) return;

                                                                                                                                                                                                                                                                                            const messageText = message.trim();
                                                                                                                                                                                                                                                                                                setMessage('');
                                                                                                                                                                                                                                                                                                    setSending(true);
                                                                                                                                                                                                                                                                                                        setAiTyping(true);

                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                  const response = await aiManager.sendMessage(id, messageText, {
                                                                                                                                                                                                                                                                                                                          temperature: 0.7,
                                                                                                                                                                                                                                                                                                                                  maxTokens: 500,
                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                              if (response.success) {
                                                                                                                                                                                                                                                                                                                                                      setMessages(prev => [response.message, ...prev]);

                                                                                                                                                                                                                                                                                                                                                              await trackEvent('ai_message_sent', {
                                                                                                                                                                                                                                                                                                                                                                        chat_id: id,
                                                                                                                                                                                                                                                                                                                                                                                  ai_id: chat.aiId,
                                                                                                                                                                                                                                                                                                                                                                                            message_length: messageText.length,
                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                            setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                      scrollViewRef.current?.scrollTo({ y: 0, animated: true });
                                                                                                                                                                                                                                                                                                                                                                                                                              }, 100);
                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                            Alert.alert('Erreur', response.error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    setMessage(messageText);
                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                              } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error(error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Alert.alert('Erreur', 'Une erreur est survenue');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setMessage(messageText);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } finally {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setSending(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setAiTyping(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const handleQuotaExceeded = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Alert.alert(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'Quota atteint',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'Tu as utilisé toutes tes requêtes IA pour aujourd’hui.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      { text: 'Plus tard', style: 'cancel' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              { text: 'Voir Premium', onPress: () => router.push('/premium/subscribe') },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const renderHeader = () => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <View style={[styles.header, { backgroundColor: colors.surface }]}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <TouchableOpacity onPress={() => router.back()}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Ionicons name="chevron-back" size={28} color={colors.textPrimary} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </TouchableOpacity>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <View style={styles.headerCenter}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Text style={[styles.aiName, { color: colors.textPrimary }]}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {chat?.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Text style={[styles.aiStatus, { color: colors.textSecondary }]}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {aiTyping ? 'En train de répondre...' : 'En ligne'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </View>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <TouchableOpacity
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onPress={() =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Alert.alert('Options', 'Fonctionnalité à venir', [{ text: 'OK' }])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Ionicons name="ellipsis-horizontal" size={24} color={colors.textPrimary} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const renderMessages = () => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <ScrollView
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ref={scrollViewRef}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                inverted
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      contentContainerStyle={styles.messagesContent}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {aiTyping && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <View style={styles.typingIndicator}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Text style={{ color: colors.textSecondary }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {chat?.title} réfléchit...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {messages.map(msg => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <MessageBubble
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              key={msg.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        message={msg}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  isOwn={msg.role === 'user'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </ScrollView>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                 }
 