// lib/messaging/message-store.js

/**
 *  * Gestionnaire de stockage local des messages
  * Utilise MMKV pour des performances optimales
   */

   import { MMKV } from 'react-native-mmkv';
   import { localStore } from '../storage/local-storage';

   const MESSAGES_STORAGE_KEY = 'otakus_messages';
   const CHATS_STORAGE_KEY = 'otakus_chats';
   const UNREAD_COUNTS_KEY = 'otakus_unread_counts';

   class MessageStore {
     constructor() {
         this.storage = new MMKV();
             this.userId = null;
               }

                 /**
                    * Initialiser le store avec l'ID utilisateur
                       */
                         async initialize(userId) {
                             this.userId = userId;
                                 
                                     // Initialiser les structures de données si nécessaire
                                         if (!this.storage.contains(MESSAGES_STORAGE_KEY)) {
                                               this.storage.set(MESSAGES_STORAGE_KEY, JSON.stringify({}));
                                                   }
                                                       
                                                           if (!this.storage.contains(CHATS_STORAGE_KEY)) {
                                                                 this.storage.set(CHATS_STORAGE_KEY, JSON.stringify({}));
                                                                     }
                                                                         
                                                                             if (!this.storage.contains(UNREAD_COUNTS_KEY)) {
                                                                                   this.storage.set(UNREAD_COUNTS_KEY, JSON.stringify({}));
                                                                                       }
                                                                                           
                                                                                               // Nettoyer les vieux messages (plus de 30 jours)
                                                                                                   await this.cleanupOldMessages();
                                                                                                     }

                                                                                                       /**
                                                                                                          * Sauvegarder un message
                                                                                                             */
                                                                                                               async saveMessage(chatId, message) {
                                                                                                                   try {
                                                                                                                         // Récupérer les messages existants
                                                                                                                               const messagesData = JSON.parse(this.storage.getString(MESSAGES_STORAGE_KEY) || '{}');
                                                                                                                                     
                                                                                                                                           if (!messagesData[chatId]) {
                                                                                                                                                   messagesData[chatId] = [];
                                                                                                                                                         }
                                                                                                                                                               
                                                                                                                                                                     // Vérifier si le message existe déjà
                                                                                                                                                                           const existingIndex = messagesData[chatId].findIndex(m => m.id === message.id);
                                                                                                                                                                                 
                                                                                                                                                                                       if (existingIndex >= 0) {
                                                                                                                                                                                               // Mettre à jour le message existant
                                                                                                                                                                                                       messagesData[chatId][existingIndex] = message;
                                                                                                                                                                                                             } else {
                                                                                                                                                                                                                     // Ajouter le nouveau message
                                                                                                                                                                                                                             messagesData[chatId].push(message);
                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                             // Mettre à jour le compteur de non-lus si le message n'est pas de l'utilisateur
                                                                                                                                                                                                                                                     if (message.senderId !== this.userId && message.status !== 'read') {
                                                                                                                                                                                                                                                               await this.incrementUnreadCount(chatId);
                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                         // Limiter le nombre de messages par chat (500 max)
                                                                                                                                                                                                                                                                                               if (messagesData[chatId].length > 500) {
                                                                                                                                                                                                                                                                                                       messagesData[chatId] = messagesData[chatId].slice(-500);
                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                         // Sauvegarder
                                                                                                                                                                                                                                                                                                                               this.storage.set(MESSAGES_STORAGE_KEY, JSON.stringify(messagesData));
                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                           // Mettre à jour les métadonnées du chat
                                                                                                                                                                                                                                                                                                                                                 await this.updateChatMetadata(chatId, {
                                                                                                                                                                                                                                                                                                                                                         lastMessage: message,
                                                                                                                                                                                                                                                                                                                                                                 updatedAt: Date.now(),
                                                                                                                                                                                                                                                                                                                                                                       });
                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                   return true;
                                                                                                                                                                                                                                                                                                                                                                                       } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                             console.error('Save message error:', error);
                                                                                                                                                                                                                                                                                                                                                                                                   return false;
                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                           /**
                                                                                                                                                                                                                                                                                                                                                                                                              * Récupérer les messages d'un chat
                                                                                                                                                                                                                                                                                                                                                                                                                 */
                                                                                                                                                                                                                                                                                                                                                                                                                   async getMessages(chatId, limit = 50, before = null) {
                                                                                                                                                                                                                                                                                                                                                                                                                       try {
                                                                                                                                                                                                                                                                                                                                                                                                                             const messagesData = JSON.parse(this.storage.getString(MESSAGES_STORAGE_KEY) || '{}');
                                                                                                                                                                                                                                                                                                                                                                                                                                   let messages = messagesData[chatId] || [];
                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                               // Filtrer par timestamp si 'before' est spécifié
                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (before) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                             messages = messages.filter(m => m.timestamp < before);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               // Trier par timestamp (plus ancien en premier pour l'affichage)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     messages.sort((a, b) => a.timestamp - b.timestamp);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // Limiter le nombre de résultats
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (limit > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               messages = messages.slice(-limit);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return messages;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           console.error('Get messages error:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     