// lib/auth/auth-context.jsx
/**
 *  * Contexte d'authentification global
  * Gère l'état de l'utilisateur, la session et les tokens
   */

   import React, { createContext, useContext, useState, useEffect } from 'react';
   import { Alert } from 'react-native';
   import * as SecureStore from 'expo-secure-store';
   import { 
     GoogleSignin,
       statusCodes 
       } from '@react-native-google-signin/google-signin';
       import * as AppleAuthentication from 'expo-apple-authentication';
       import { authApi } from '../api/endpoints';

       // Clés de stockage sécurisé
       const AUTH_TOKEN_KEY = 'otakus_nexus_auth_token';
       const USER_DATA_KEY = 'otakus_nexus_user_data';
       const REFRESH_TOKEN_KEY = 'otakus_nexus_refresh_token';

       const AuthContext = createContext({
         user: null,
           loading: true,
             signIn: async () => {},
               signUp: async () => {},
                 signOut: async () => {},
                   updateUser: async () => {},
                   });

                   export function AuthProvider({ children }) {
                     const [user, setUser] = useState(null);
                       const [loading, setLoading] = useState(true);
                         const [token, setToken] = useState(null);

                           // Configuration Google Sign-In
                             useEffect(() => {
                                 GoogleSignin.configure({
                                       webClientId: process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID,
                                             iosClientId: process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID,
                                                   offlineAccess: true,
                                                       });
                                                         }, []);

                                                           // Vérifier l'authentification au démarrage
                                                             useEffect(() => {
                                                                 checkAuthState();
                                                                   }, []);
                        const checkAuthState = async () => {
                                try {
                                      // Récupérer le token depuis le stockage sécurisé
                                            const storedToken = await SecureStore.getItemAsync(AUTH_TOKEN_KEY);
                                                  const storedUser = await SecureStore.getItemAsync(USER_DATA_KEY);

                                                        if (storedToken && storedUser) {
                                                                // Vérifier la validité du token
                                                                        const isValid = await validateToken(storedToken);
                                                                                
                                                                                        if (isValid) {
                                                                                                  setToken(storedToken);
                                                                                                            setUser(JSON.parse(storedUser));
                                                                                                                    } else {
                                                                                                                              // Token invalide, tenter un refresh
                                                                                                                                        await refreshToken();
                                                                                                                                                }
                                                                                                                                                      }
                                                                                                                                                          } catch (error) {
                                                                                                                                                                console.error('Error checking auth state:', error);
                                                                                                                                                                    } finally {
                                                                                                                                                                          setLoading(false);
                                                                                                                                                                              }
                                                                                                                                                                                };

                                                                                                                                                                                  const validateToken = async (token) => {
                                                                                                                                                                                      try {
                                                                                                                                                                                            // Implémentation simplifiée - en production, vérifier auprès du backend
                                                                                                                                                                                                  // Pour l'instant, on vérifie juste si le token existe
                                                                                                                                                                                                        return !!token && token.length > 10;
                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                  return false;
                                                                                                                                                                                                                      }
                                                                                                                                                                                                                        };

                                                                                                                                                                                                                          const refreshToken = async () => {
                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                    const refreshToken = await SecureStore.getItemAsync(REFRESH_TOKEN_KEY);
                                                                                                                                                                                                                                          if (!refreshToken) {
                                                                                                                                                                                                                                                  throw new Error('No refresh token available');
                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                              // Appel API pour rafraîchir le token
                                                                                                                                                                                                                                                                    const response = await authApi.refreshToken(refreshToken);
                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                if (response.success) {
                                                                                                                                                                                                                                                                                        await SecureStore.setItemAsync(AUTH_TOKEN_KEY, response.token);
                                                                                                                                                                                                                                                                                                await SecureStore.setItemAsync(REFRESH_TOKEN_KEY, response.refreshToken);
                                                                                                                                                                                                                                                                                                        setToken(response.token);
                                                                                                                                                                                                                                                                                                                return true;
                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                          } catch (error) {
                                                                                                                                                                                                                                                                                                                                console.error('Token refresh failed:', error);
                                                                                                                                                                                                                                                                                                                                      await signOut();
                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                              return false;
                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                  const signIn = async (email, password) => {
                                                                                                                                                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                                                                                                                                                            setLoading(true);
                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                        // Appel API d'authentification
                                                                                                                                                                                                                                                                                                                                                                              const response = await authApi.signIn({ email, password });
                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                          if (response.success) {
                                                                                                                                                                                                                                                                                                                                                                                                  // Stocker les tokens
                                                                                                                                                                                                                                                                                                                                                                                                          await SecureStore.setItemAsync(AUTH_TOKEN_KEY, response.token);
                                                                                                                                                                                                                                                                                                                                                                                                                  await SecureStore.setItemAsync(REFRESH_TOKEN_KEY, response.refreshToken);
                                                                                                                                                                                                                                                                                                                                                                                                                          await SecureStore.setItemAsync(USER_DATA_KEY, JSON.stringify(response.user));
                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                          // Mettre à jour l'état
                                                                                                                                                                                                                                                                                                                                                                                                                                                  setToken(response.token);
                                                                                                                                                                                                                                                                                                                                                                                                                                                          setUser(response.user);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return { success: true, user: response.user };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        throw new Error(response.message || 'Authentication failed');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.error('Sign in error:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Alert.alert('Erreur', error.message || 'Échec de la connexion');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return { success: false, error: error.message };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } finally {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              setLoading(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const signInWithGoogle = async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Vérifier si Google Play Services sont disponibles
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      await GoogleSignin.hasPlayServices();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Connexion Google
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const userInfo = await GoogleSignin.signIn();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Récupérer le token Google
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const { idToken } = await GoogleSignin.getTokens();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // Authentifier avec notre backend
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const response = await authApi.signInWithGoogle({ idToken });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (response.success) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await SecureStore.setItemAsync(AUTH_TOKEN_KEY, response.token);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await SecureStore.setItemAsync(REFRESH_TOKEN_KEY, response.refreshToken);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await SecureStore.setItemAsync(USER_DATA_KEY, JSON.stringify(response.user));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setToken(response.token);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setUser(response.user);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return { success: true, user: response.user };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (error.code === statusCodes.SIGN_IN_CANCELLED) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log('Google sign-in cancelled');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.error('Google sign-in error:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Alert.alert('Erreur', 'Échec de la connexion avec Google');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return { success: false, error: error.message };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                        const signInWithApple = async () => {
                                  try {
                                        // Vérifier la disponibilité d'Apple Sign-In
                                              const isAvailable = await AppleAuthentication.isAvailableAsync();
                                                    
                                                          if (!isAvailable) {
                                                                  Alert.alert('Erreur', 'Apple Sign-In n\'est pas disponible');
                                                                          return { success: false, error: 'Apple Sign-In not available' };
                                                                                }
                                                                                      
                                                                                            // Connexion Apple
                                                                                                  const credential = await AppleAuthentication.signInAsync({
                                                                                                          requestedScopes: [
                                                                                                                    AppleAuthentication.AppleAuthenticationScope.FULL_NAME,
                                                                                                                              AppleAuthentication.AppleAuthenticationScope.EMAIL,
                                                                                                                                      ],
                                                                                                                                            });
                                                                                                                                                  
                                                                                                                                                        // Authentifier avec notre backend
                                                                                                                                                              const response = await authApi.signInWithApple({
                                                                                                                                                                      identityToken: credential.identityToken,
                                                                                                                                                                              userIdentifier: credential.user,
                                                                                                                                                                                      email: credential.email,
                                                                                                                                                                                              fullName: credential.fullName,
                                                                                                                                                                                                    });
                                                                                                                                                                                                          
                                                                                                                                                                                                                if (response.success) {
                                                                                                                                                                                                                        await SecureStore.setItemAsync(AUTH_TOKEN_KEY, response.token);
                                                                                                                                                                                                                                await SecureStore.setItemAsync(REFRESH_TOKEN_KEY, response.refreshToken);
                                                                                                                                                                                                                                        await SecureStore.setItemAsync(USER_DATA_KEY, JSON.stringify(response.user));
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                        setToken(response.token);
                                                                                                                                                                                                                                                                setUser(response.user);
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                return { success: true, user: response.user };
                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                          } catch (error) {
                                                                                                                                                                                                                                                                                                console.error('Apple sign-in error:', error);
                                                                                                                                                                                                                                                                                                      Alert.alert('Erreur', 'Échec de la connexion avec Apple');
                                                                                                                                                                                                                                                                                                            return { success: false, error: error.message };
                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                    const signUp = async (userData) => {
                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                              setLoading(true);
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                          // Appel API d'inscription
                                                                                                                                                                                                                                                                                                                                                const response = await authApi.signUp(userData);
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                            if (response.success) {
                                                                                                                                                                                                                                                                                                                                                                    // Automatiquement connecter après l'inscription
                                                                                                                                                                                                                                                                                                                                                                            await signIn(userData.email, userData.password);
                                                                                                                                                                                                                                                                                                                                                                                    return { success: true };
                                                                                                                                                                                                                                                                                                                                                                                          } else {
                                                                                                                                                                                                                                                                                                                                                                                                  throw new Error(response.message || 'Registration failed');
                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                  console.error('Sign up error:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                        Alert.alert('Erreur', error.message || 'Échec de l\'inscription');
                                                                                                                                                                                                                                                                                                                                                                                                                              return { success: false, error: error.message };
                                                                                                                                                                                                                                                                                                                                                                                                                                  } finally {
                                                                                                                                                                                                                                                                                                                                                                                                                                        setLoading(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                              };


                                                                                                                                                                                                                                                                                                                              
                        const signOut = async () => {
                                  try {
                                        setLoading(true);
                                              
                                                    // Déconnexion Google si connecté avec Google
                                                          try {
                                                                  await GoogleSignin.signOut();
                                                                        } catch (googleError) {
                                                                                console.log('Google sign-out failed:', googleError);
                                                                                      }
                                                                                            
                                                                                                  // Appel API de déconnexion
                                                                                                        await authApi.signOut(token);
                                                                                                              
                                                                                                                    // Supprimer les données locales
                                                                                                                          await SecureStore.deleteItemAsync(AUTH_TOKEN_KEY);
                                                                                                                                await SecureStore.deleteItemAsync(REFRESH_TOKEN_KEY);
                                                                                                                                      await SecureStore.deleteItemAsync(USER_DATA_KEY);
                                                                                                                                            
                                                                                                                                                  // Réinitialiser l'état
                                                                                                                                                        setUser(null);
                                                                                                                                                              setToken(null);
                                                                                                                                                                    
                                                                                                                                                                        } catch (error) {
                                                                                                                                                                              console.error('Sign out error:', error);
                                                                                                                                                                                    // Forcer la déconnexion même en cas d'erreur
                                                                                                                                                                                          await SecureStore.deleteItemAsync(AUTH_TOKEN_KEY);
                                                                                                                                                                                                await SecureStore.deleteItemAsync(REFRESH_TOKEN_KEY);
                                                                                                                                                                                                      await SecureStore.deleteItemAsync(USER_DATA_KEY);
                                                                                                                                                                                                            setUser(null);
                                                                                                                                                                                                                  setToken(null);
                                                                                                                                                                                                                      } finally {
                                                                                                                                                                                                                            setLoading(false);
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                    const updateUser = async (updates) => {
                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                              // Appel API de mise à jour
                                                                                                                                                                                                                                                    const response = await authApi.updateUser(user.id, updates, token);
                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                if (response.success) {
                                                                                                                                                                                                                                                                        const updatedUser = { ...user, ...updates };
                                                                                                                                                                                                                                                                                await SecureStore.setItemAsync(USER_DATA_KEY, JSON.stringify(updatedUser));
                                                                                                                                                                                                                                                                                        setUser(updatedUser);
                                                                                                                                                                                                                                                                                                return { success: true, user: updatedUser };
                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                          } catch (error) {
                                                                                                                                                                                                                                                                                                                console.error('Update user error:', error);
                                                                                                                                                                                                                                                                                                                      return { success: false, error: error.message };
                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                  <AuthContext.Provider
                                                                                                                                                                                                                                                                                                                                        value={{
                                                                                                                                                                                                                                                                                                                                                user,
                                                                                                                                                                                                                                                                                                                                                        loading,
                                                                                                                                                                                                                                                                                                                                                                token,
                                                                                                                                                                                                                                                                                                                                                                        signIn,
                                                                                                                                                                                                                                                                                                                                                                                signInWithGoogle,
                                                                                                                                                                                                                                                                                                                                                                                        signInWithApple,
                                                                                                                                                                                                                                                                                                                                                                                                signUp,
                                                                                                                                                                                                                                                                                                                                                                                                        signOut,
                                                                                                                                                                                                                                                                                                                                                                                                                updateUser,
                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                {children}
                                                                                                                                                                                                                                                                                                                                                                                                                                    </AuthContext.Provider>
                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                      export function useAuth() {
                                                                                                                                                                                                                                                                                                                                                                                                                                        const context = useContext(AuthContext);
                                                                                                                                                                                                                                                                                                                                                                                                                                          if (!context) {
                                                                                                                                                                                                                                                                                                                                                                                                                                              throw new Error('useAuth must be used within an AuthProvider');
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                  return context;
                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       